---

- hosts: all
  become: yes
  vars:
    packages_to_install:
      - composer-cli
      - osbuild
      - osbuild-composer
  tasks:

    - name: Enable fastestmirror
      ini_file:
        path: /etc/dnf/dnf.conf
        section: main
        option: fastestmirror
        value: "1"
    
    - name: Update all packages
      package:
        name: "*"
        state: latest

    - name: Install packages
      package:
        name: "{{ packages_to_install }}"
        state: present
    
    - name: Start osbuild-composer
      service:
        name: osbuild-composer.socket
        state: started
        enabled: yes