name: Image Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  vagrant-up:
    runs-on: macos-10.15

    steps:
      - uses: actions/checkout@v2

      - name: Cache Vagrant boxes
        uses: actions/cache@v2
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
          restore-keys: |
            ${{ runner.os }}-vagrant-

      - name: Run vagrant up
        run: vagrant up

      - name: ssh into box after boot
        run: |
          vagrant ssh -c "cat /etc/centos-release"  
          vagrant ssh -c "echo 'fastestmirror=1' | sudo tee -a /etc/dnf/dnf.conf"
          vagrant ssh -c "sudo dnf -qy upgrade"
          vagrant ssh -c "sudo dnf -qy composer-cli osbuild osbuild-composer"
          vagrant ssh -c "cat /etc/centos-release"