name: Image Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  vagrant-up:
    runs-on: macos-10.15

    steps:
      - uses: actions/checkout@v2

      - name: Cache Vagrant boxes
        uses: actions/cache@v2
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
          restore-keys: |
            ${{ runner.os }}-vagrant-

      - name: Add vagrant disk size plugin
        run: vagrant plugin install vagrant-disksize

      - name: Start vagrant box
        run: vagrant up

      - name: Build image
        run: vagrant ssh -c "/vagrant/build-image.sh"

      - name: Check built image
        run: ls -alhR output