name: Image Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  vagrant-up:
    runs-on: macos-10.15

    steps:
      - uses: actions/checkout@v2

      - name: Cache Vagrant boxes
        uses: actions/cache@v2
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
          restore-keys: |
            ${{ runner.os }}-vagrant-

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip
          restore-keys: |
            ${{ runner.os }}-pip-

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Upgrade pip + wheel
        run: pip install -U pip wheel

      - name: Install ansible
        run: |
          pip wheel ansible
          pip install ansible

      - name: Start vagrant box
        run: vagrant up

      - name: Verify composer is running
        run: vagrant ssh -c "sudo composer-cli status show"
