name: Image Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Install packages
        run: |
          sudo apt install -y bridge-utils libvirt-clients libvirt-daemon \
            libvirt-daemon-system libvirt-daemon-driver-qemu qemu-kvm virtinst
